### ISSUE TITLE
Mathematica Jupyter integration tutorial does not work 

### ISSUE THREAD

**Issue by berndmeyer** [sagemathinc/cocalc-howto#3]
I've just tried to install the Matheamtica (Sorry, Wolfram engine) integration for Jupyter as described in the tutorial. However, the install fails (already in the early stages, as libraries seem to be missing):

Reading state information... Done
Package libasound2 is a virtual package provided by:
  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
You should explicitly select one to install.

Package libgl1-mesa-glx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

This later on leads to the engine being unable to start up:

usr/local/Wolfram/WolframEngine/13.3/SystemFiles/FrontEnd/Binaries/Linux-x86-64/WolframPlayer: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by williamstein** [comment]
@berndmeyer Thanks!  I've fully updated and tested the tutorial now, and it works.  It includes supporting Mathematica 14, the new Ubuntu 24.04, and I tested graphics in a Jupyter notebook, etc.

If you hit any issues, let us know in support (help@cocalc.com)

**Comment by berndmeyer** [comment]
Fantastic, works like a charm. Thanks!
However, please note that the instructions in the tutorial install Wolfram Engine Version 13.3 but the example commands further down assume that Version 14 was installed.

**Comment by williamstein** [comment]
> However, please note that the instructions in the tutorial install Wolfram Engine Version 13.3 but the example commands further down assume that Version 14 was installed.

Thanks.  There should be no mention of version 13.x anymore.
